name: Mindplace
favicon: null
layout_spectrum: 0.2740345485508442
typography_spectrum: 0.4848712112288922
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9831516754347831
  lightness: 0.03482157574035227
  saturation: 0.5501639160793275
  rhythmicContrast: 0.003710595890879631
purpose: []
